[#nf_hist-make_path]
= xref:nf_hist.adoc[nf&lowbar;hist]::make&lowbar;path
:relfileprefix: ../
:mrdocs:

Used to create a path to some element within the source data class, typically used for creating notification methods or tracked sub&hyphen;elements e&period;g&period; using my&lowbar;path &equals; nf&colon;&colon;make&lowbar;path&lt;decltype(root&hyphen;&gt;my&lowbar;collection&lsqb;0&rsqb;&period;my&lowbar;field)&gt;&semi; or&period;&period;&period; using my&lowbar;path &equals; NF&lowbar;PATH(root&hyphen;&gt;my&lowbar;collection&lsqb;0&rsqb;&period;my&lowbar;field)&semi;

== Synopsis

Declared in `&lt;nf&sol;hist&period;h&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class Input&gt;
using make&lowbar;path = path&lowbar;tagged&lowbar;keys&lt;Input::nf&lowbar;keys, Input::nf&lowbar;path, Input::nf&lowbar;editor&lowbar;type&gt;;
----

== Template Parameters

[cols=2]
|===
| Name
| Description
| *Input*
| the path to a given element within the source data class (represented as a type stored at compile time), from within a tracked type use decltype(root&hyphen;&gt;my&lowbar;path&lowbar;to&lowbar;elem)
|===


[.small]#Created with https://www.mrdocs.com[MrDocs]#
